#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  6 19:03:05 2026

@author: leszekwierzchleyski
"""

"""Import Libraries"""

import numpy as np
import torch
from transformers import BertModel, BertTokenizer
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
import lightgbm as lgb



if __name__ == "__main__": 
    
    """"Prepare device, dataframeme, tokeniser, and model"""

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    filename = 'potential-talents - Aspiring human resources - seeking human resources.csv'
    df = pd.read_csv(filename)

    print(df.head())

    bert_version = 'bert-large-cased'
    tokenizer = BertTokenizer.from_pretrained(bert_version)
    model = BertModel.from_pretrained(bert_version)
    model = model.eval()
    model = model.to(device)



    """Tokenise and embed"""
    
    txt = []

    for i in range(len(df)):
        txt.append(df['job_title'][i])
    txt.append('aspiring human resources')




    encodings = tokenizer(
        txt, 
        padding=True, 
        return_tensors='pt' 
    )


    encodings = encodings.to(device)
    encodings.keys()
    encodings['input_ids']
    encodings['attention_mask']
    encodings['token_type_ids']




    with torch.no_grad():
       
        embeds = model(**encodings)
        


        embeds = embeds[0]
    MEANS = embeds.mean(dim=1)


    """Calculate cosine similarities and find mean vectors."""

    sim = []


    for i in range(len(MEANS)-1):
         similarity = torch.cosine_similarity(MEANS[i].unsqueeze(0), MEANS[-1].unsqueeze(0))
         sim.append(similarity[0])


    MEANS_Final = MEANS[:-1]



    decompose = PCA(n_components=10)

    MEANS_dec = decompose.fit(MEANS_Final)





    MEANS_list = []
    for i in range(len(MEANS_Final)):
        MEANS_list.append(MEANS_Final[i].numpy())






    df['mean'] = MEANS_list
    df['similarity']=sim

    sorted_df = df.sort_values(by='similarity',   ascending=False)


    """Assign ranks for each row in dataframe (labels for training) and use 
    PCA to reduce size of imput tensors. """

    ranks = np.linspace(1, len(df), len(df))
    sorted_df['rank']=ranks
   
    print(sorted_df.head())  


    z = sorted_df['mean']

    array_frame = pd.DataFrame(pd.Series(z.iloc[0])).T
    for i in range(1, len(z)):
        a = pd.DataFrame(pd.Series(z.iloc[i])).T
        array_frame = pd.concat([array_frame, a])

    x_dec = decompose.fit(array_frame.values)


    x_input = x_dec.transform(array_frame)


    """Create input dataframe"""


    col_1 = []
    col_2 = []
    col_3 = []
    col_4 = []
    col_5 = []
    col_6 = []
    col_7 = []
    col_8 = []
    col_9 = []
    col_10 = []

    for i in range(len(x_input)):
      
        col_1.append(x_input[i][0])
        col_2.append(x_input[i][1])
        col_3.append(x_input[i][2])
        col_4.append(x_input[i][3])
        col_5.append(x_input[i][4])
        col_6.append(x_input[i][5])
        col_7.append(x_input[i][6])
        col_8.append(x_input[i][7])
        col_9.append(x_input[i][8])
        col_10.append(x_input[i][9])
    print(col_1)



    sorted_df['col_1'] = col_1
    sorted_df['col_2'] = col_2
    sorted_df['col_3'] = col_3
    sorted_df['col_4'] = col_4
    sorted_df['col_5'] = col_5
    sorted_df['col_6'] = col_6
    sorted_df['col_7'] = col_7
    sorted_df['col_8'] = col_8
    sorted_df['col_9'] = col_9
    sorted_df['col_10'] = col_10
    

    x = sorted_df.drop(columns=['job_title', 'id', 'similarity', 'rank', 
                                  'location', 'fit', 'connection', 'mean'])

    y = sorted_df['rank']


    """Ranking algorithm"""

    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
    
    
    gbm = lgb.LGBMRanker(label_gain=[i for i in range(x_train.shape[0]+x_test.shape[0]+1)])
    query_train = [x_train.shape[0]]

    query_test = [x_test.shape[0]]

    gbm.fit(x_train, y_train, 
             group=[83],
             eval_set=[(x_test, y_test)], 
             eval_group=[query_test],
             eval_at=[10, 15, 20])
    
    """Output results"""
    
    predictions = gbm.predict(x_test)
    predict_df = pd.DataFrame({'Prediction': [predictions], 'label': [y_test]})
    sorted_predict = predict_df.sort_values(by='Prediction',   ascending=False)
    x_test['ranks'] = gbm.predict(x_test)
    x_test['labels'] = y_test
    results = x_test.sort_values(by='ranks').reset_index()
    print(results)
  
